// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.CheckResults');
goog.provide('proto.com.watcourses.wat_courses.proto.CheckResults.Issue');
goog.provide('proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.CheckResults = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.CheckResults.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.CheckResults, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.CheckResults.displayName = 'proto.com.watcourses.wat_courses.proto.CheckResults';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.CheckResults.Issue.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.CheckResults.Issue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.CheckResults.Issue.displayName = 'proto.com.watcourses.wat_courses.proto.CheckResults.Issue';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.CheckResults.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.CheckResults.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CheckResults.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuesList: jspb.Message.toObjectList(msg.getIssuesList(),
    proto.com.watcourses.wat_courses.proto.CheckResults.Issue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.CheckResults;
  return proto.com.watcourses.wat_courses.proto.CheckResults.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.watcourses.wat_courses.proto.CheckResults.Issue;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.CheckResults.Issue.deserializeBinaryFromReader);
      msg.addIssues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.CheckResults.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CheckResults.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.watcourses.wat_courses.proto.CheckResults.Issue.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.CheckResults.Issue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    subjectName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    relatedCond: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    relatedCondRaw: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    relatedCourseList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    relatedCourseListList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.CheckResults.Issue;
  return proto.com.watcourses.wat_courses.proto.CheckResults.Issue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubjectName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRelatedCond(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRelatedCondRaw(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addRelatedCourse(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addRelatedCourseList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.CheckResults.Issue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRelatedCourseList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getRelatedCourseListList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type = {
  PRE_REQUISITE_NOT_MET: 1,
  CO_REQUISITE_NOT_MET: 2,
  ANTI_REQUISITE_NOT_MET: 3,
  DEGREE_REQUIREMENTS_NOT_MET: 4
};

/**
 * optional Type type = 1;
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getType = function() {
  return /** @type {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue.Type} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string subject_name = 2;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getSubjectName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setSubjectName = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearSubjectName = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.hasSubjectName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string related_cond = 3;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getRelatedCond = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setRelatedCond = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearRelatedCond = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.hasRelatedCond = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string related_cond_raw = 4;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getRelatedCondRaw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setRelatedCondRaw = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearRelatedCondRaw = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.hasRelatedCondRaw = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string related_course = 5;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getRelatedCourseList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setRelatedCourseList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.addRelatedCourse = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearRelatedCourseList = function() {
  return this.setRelatedCourseList([]);
};


/**
 * repeated string related_course_list = 6;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.getRelatedCourseListList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.setRelatedCourseListList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.addRelatedCourseList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.Issue.prototype.clearRelatedCourseListList = function() {
  return this.setRelatedCourseListList([]);
};


/**
 * repeated Issue issues = 1;
 * @return {!Array<!proto.com.watcourses.wat_courses.proto.CheckResults.Issue>}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.getIssuesList = function() {
  return /** @type{!Array<!proto.com.watcourses.wat_courses.proto.CheckResults.Issue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.watcourses.wat_courses.proto.CheckResults.Issue, 1));
};


/**
 * @param {!Array<!proto.com.watcourses.wat_courses.proto.CheckResults.Issue>} value
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults} returns this
*/
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.setIssuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults.Issue}
 */
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.addIssues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.watcourses.wat_courses.proto.CheckResults.Issue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.CheckResults} returns this
 */
proto.com.watcourses.wat_courses.proto.CheckResults.prototype.clearIssuesList = function() {
  return this.setIssuesList([]);
};


