// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.CourseSection');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.CourseSection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.CourseSection.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.CourseSection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.CourseSection.displayName = 'proto.com.watcourses.wat_courses.proto.CourseSection';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.CourseSection.repeatedFields_ = [5,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.CourseSection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.CourseSection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CourseSection.toObject = function(includeInstance, msg) {
  var f, obj = {
    section: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    location: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    enrolCap: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    enrolTotal: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    timeList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    room: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    instructor: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    sectionid: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    reservedEnrolInfoList: jspb.Message.toObjectList(msg.getReservedEnrolInfoList(),
    proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.CourseSection;
  return proto.com.watcourses.wat_courses.proto.CourseSection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.CourseSection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSection(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEnrolCap(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEnrolTotal(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoom(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstructor(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSectionid(value);
      break;
    case 9:
      var value = new proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.deserializeBinaryFromReader);
      msg.addReservedEnrolInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.CourseSection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.CourseSection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.CourseSection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getTimeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getReservedEnrolInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string section = 1;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getSection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setSection = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearSection = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasSection = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string location = 2;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setLocation = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearLocation = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 enrol_cap = 3;
 * @return {number}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getEnrolCap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setEnrolCap = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearEnrolCap = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasEnrolCap = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 enrol_total = 4;
 * @return {number}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getEnrolTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setEnrolTotal = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearEnrolTotal = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasEnrolTotal = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string time = 5;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getTimeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setTimeList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.addTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearTimeList = function() {
  return this.setTimeList([]);
};


/**
 * optional string room = 6;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getRoom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setRoom = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearRoom = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasRoom = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string instructor = 7;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getInstructor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setInstructor = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearInstructor = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasInstructor = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int32 sectionId = 8;
 * @return {number}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getSectionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setSectionid = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearSectionid = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.hasSectionid = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated ReservedEnrolInfo reserved_enrol_info = 9;
 * @return {!Array<!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo>}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.getReservedEnrolInfoList = function() {
  return /** @type{!Array<!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo, 9));
};


/**
 * @param {!Array<!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo>} value
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
*/
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.setReservedEnrolInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo}
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.addReservedEnrolInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.CourseSection} returns this
 */
proto.com.watcourses.wat_courses.proto.CourseSection.prototype.clearReservedEnrolInfoList = function() {
  return this.setReservedEnrolInfoList([]);
};


