// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.displayName = 'proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    reserve: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    cap: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    total: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo;
  return proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReserve(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCap(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string reserve = 1;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.getReserve = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.setReserve = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.clearReserve = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.hasReserve = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 cap = 2;
 * @return {number}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.getCap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.setCap = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.clearCap = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.hasCap = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 total = 3;
 * @return {number}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.setTotal = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo} returns this
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.clearTotal = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.ReservedEnrolInfo.prototype.hasTotal = function() {
  return jspb.Message.getField(this, 3) != null;
};


