// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.Schedule');
goog.provide('proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.Schedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.Schedule.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.Schedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.Schedule.displayName = 'proto.com.watcourses.wat_courses.proto.Schedule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.displayName = 'proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.Schedule.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.Schedule.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.Schedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.Schedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    termsList: jspb.Message.toObjectList(msg.getTermsList(),
    proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule}
 */
proto.com.watcourses.wat_courses.proto.Schedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.Schedule;
  return proto.com.watcourses.wat_courses.proto.Schedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule}
 */
proto.com.watcourses.wat_courses.proto.Schedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.deserializeBinaryFromReader);
      msg.addTerms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.Schedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.Schedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.Schedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTermsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    courseCodesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    termName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule;
  return proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addCourseCodes(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTermName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCourseCodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated string course_codes = 1;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.getCourseCodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.setCourseCodesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.addCourseCodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.clearCourseCodesList = function() {
  return this.setCourseCodesList([]);
};


/**
 * optional string term_name = 2;
 * @return {string}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.getTermName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.setTermName = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.clearTermName = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule.prototype.hasTermName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated TermSchedule terms = 1;
 * @return {!Array<!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule>}
 */
proto.com.watcourses.wat_courses.proto.Schedule.prototype.getTermsList = function() {
  return /** @type{!Array<!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule, 1));
};


/**
 * @param {!Array<!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule>} value
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule} returns this
*/
proto.com.watcourses.wat_courses.proto.Schedule.prototype.setTermsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule}
 */
proto.com.watcourses.wat_courses.proto.Schedule.prototype.addTerms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.watcourses.wat_courses.proto.Schedule.TermSchedule, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.Schedule} returns this
 */
proto.com.watcourses.wat_courses.proto.Schedule.prototype.clearTermsList = function() {
  return this.setTermsList([]);
};


