// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.SearchCourseResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.watcourses.wat_courses.proto.CourseInfo');
goog.require('proto.com.watcourses.wat_courses.proto.PaginationInfoResponse');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.SearchCourseResponse.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.SearchCourseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.SearchCourseResponse.displayName = 'proto.com.watcourses.wat_courses.proto.SearchCourseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.SearchCourseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && proto.com.watcourses.wat_courses.proto.PaginationInfoResponse.toObject(includeInstance, f),
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.com.watcourses.wat_courses.proto.CourseInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.SearchCourseResponse;
  return proto.com.watcourses.wat_courses.proto.SearchCourseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.watcourses.wat_courses.proto.PaginationInfoResponse;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.PaginationInfoResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    case 2:
      var value = new proto.com.watcourses.wat_courses.proto.CourseInfo;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.CourseInfo.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.SearchCourseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.watcourses.wat_courses.proto.PaginationInfoResponse.serializeBinaryToWriter
    );
  }
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.com.watcourses.wat_courses.proto.CourseInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional PaginationInfoResponse pagination = 1;
 * @return {?proto.com.watcourses.wat_courses.proto.PaginationInfoResponse}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.getPagination = function() {
  return /** @type{?proto.com.watcourses.wat_courses.proto.PaginationInfoResponse} */ (
    jspb.Message.getWrapperField(this, proto.com.watcourses.wat_courses.proto.PaginationInfoResponse, 1));
};


/**
 * @param {?proto.com.watcourses.wat_courses.proto.PaginationInfoResponse|undefined} value
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} returns this
*/
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} returns this
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CourseInfo results = 2;
 * @return {!Array<!proto.com.watcourses.wat_courses.proto.CourseInfo>}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.com.watcourses.wat_courses.proto.CourseInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.watcourses.wat_courses.proto.CourseInfo, 2));
};


/**
 * @param {!Array<!proto.com.watcourses.wat_courses.proto.CourseInfo>} value
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} returns this
*/
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.watcourses.wat_courses.proto.CourseInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.CourseInfo}
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.watcourses.wat_courses.proto.CourseInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.SearchCourseResponse} returns this
 */
proto.com.watcourses.wat_courses.proto.SearchCourseResponse.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


