// source: proto/courses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.watcourses.wat_courses.proto.StudentProfile');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.watcourses.wat_courses.proto.Schedule');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.watcourses.wat_courses.proto.StudentProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.watcourses.wat_courses.proto.StudentProfile.repeatedFields_, null);
};
goog.inherits(proto.com.watcourses.wat_courses.proto.StudentProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.watcourses.wat_courses.proto.StudentProfile.displayName = 'proto.com.watcourses.wat_courses.proto.StudentProfile';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.com.watcourses.wat_courses.proto.StudentProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.watcourses.wat_courses.proto.StudentProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    schedule: (f = msg.getSchedule()) && proto.com.watcourses.wat_courses.proto.Schedule.toObject(includeInstance, f),
    labelsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    degreesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.watcourses.wat_courses.proto.StudentProfile;
  return proto.com.watcourses.wat_courses.proto.StudentProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.watcourses.wat_courses.proto.StudentProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.watcourses.wat_courses.proto.Schedule;
      reader.readMessage(value,proto.com.watcourses.wat_courses.proto.Schedule.deserializeBinaryFromReader);
      msg.setSchedule(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addLabels(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addDegrees(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.watcourses.wat_courses.proto.StudentProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.watcourses.wat_courses.proto.StudentProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSchedule();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.watcourses.wat_courses.proto.Schedule.serializeBinaryToWriter
    );
  }
  f = message.getLabelsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getDegreesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional Schedule schedule = 1;
 * @return {?proto.com.watcourses.wat_courses.proto.Schedule}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.getSchedule = function() {
  return /** @type{?proto.com.watcourses.wat_courses.proto.Schedule} */ (
    jspb.Message.getWrapperField(this, proto.com.watcourses.wat_courses.proto.Schedule, 1));
};


/**
 * @param {?proto.com.watcourses.wat_courses.proto.Schedule|undefined} value
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
*/
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.setSchedule = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.clearSchedule = function() {
  return this.setSchedule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.hasSchedule = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string labels = 2;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.getLabelsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.setLabelsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.addLabels = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.clearLabelsList = function() {
  return this.setLabelsList([]);
};


/**
 * repeated string degrees = 3;
 * @return {!Array<string>}
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.getDegreesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.setDegreesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.addDegrees = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.watcourses.wat_courses.proto.StudentProfile} returns this
 */
proto.com.watcourses.wat_courses.proto.StudentProfile.prototype.clearDegreesList = function() {
  return this.setDegreesList([]);
};


